#!/bin/sh
#
# Run git as a dockerized application
#

set -e

VERSION="latest"
IMAGE="alpine/git:$VERSION"
CMD="/git"

# Setup volume mounts for compose config and context
if [ "$(pwd)" != '/' ]; then
    VOLUMES="-v $(pwd):$(pwd)"
fi
VOLUMES="$VOLUMES -v ${HOME}:/root"

# Only allocate tty if we detect one
if [ -t 1 ]; then
    DOCKER_RUN_OPTIONS="-t"
fi
if [ -t 0 ]; then
    DOCKER_RUN_OPTIONS="$DOCKER_RUN_OPTIONS -i"
fi

# run as local user
#DOCKER_RUN_OPTIONS=" --user $(id -u) --group-add $(id -g)  "

exec docker run $DOCKER_RUN_OPTIONS $VOLUMES -w "$(pwd)" $IMAGE "$@"
